### ISSUE TITLE
Adding Random Seed to Data Generators

### ISSUE THREAD

**Issue by adamkells** [dotimplement/HealthChain#20]
## Description
Add a random seed to the `DataGenerator` module.

## Context
There are a number of places in the code where `numpy` is used to randomly generate data. To ensure reproducibility, the user should be able to set a seed and have it flow through the code to be used by all generators.

## Possible Implementation
This will mostly involve finding all functions containing random components and adding seed as an argument to the function and then passing it to `np.random()`.

**Comment by deevyanshoo** [comment]
Hello @adamkells, I can take up this issue. Please assign this to me

**Comment by adamkells** [comment]
Hi @deevyanshoo thank you for taking an interest in contributing! 😊 We've decided to go the route of leaving issues unassigned so feel free to go ahead and start working on it. Let me know if anything is unclear or if you need help!

**Comment by ni9999** [comment]
Hi @adamkells I've added random_seed. here #80. It seems this codebase uses Faker instead of numpy to generate data
