### ISSUE TITLE
Add issue templates

### ISSUE THREAD

**Issue by jenniferjiangkells** [dotimplement/HealthChain#62]
Get Hacktoberfest ready!

**Comment by jenniferjiangkells** [comment]
https://github.com/kedro-org/kedro/tree/main/.github/ISSUE_TEMPLATE
https://github.com/Josee9988/project-template/tree/master/.github/ISSUE_TEMPLATE

**Comment by jenniferjiangkells** [comment]
@adamkells are you up for taking this as well for spoopy month

**Comment by adamkells** [comment]
spoop
