### ISSUE TITLE
Parse CDA section by code in addition to templateId

### ISSUE THREAD

**Issue by jenniferjiangkells** [dotimplement/HealthChain#66]
## Description
CDA (Clinical Document Architecture) is an XML-based standard for encoding clinical documents, designed to facilitate interoperable exchange of medical information between healthcare systems.

Currently, the CDA parser parses problems, medications, and allergies sections, using a dictionary-based internal representation via `xmltodict`. It finds sections by parsing and checking the `templateId` field in `structuredBody/Component/Section`([Reference](https://gazelle.ihe.net/CDAGenerator/cda/POCDMT000040Section.html)). However as it is not a required field, sections are sometimes not picked up. To make sure sections are picked up, we should check the `code` field as well.

### Example
This will parse as a medication section because it contains `templateId`:
https://github.com/dotimplement/HealthChain/blob/a4beb13020a66fe3b2d1b5555433dfbf0d5480f3/resources/uclh_cda.xml#L1506-L1512
This will not be parsed as a medication section because it doesn't contain `templateId`. The identifier is in the `code` field instead:
https://github.com/dotimplement/HealthChain/blob/a4beb13020a66fe3b2d1b5555433dfbf0d5480f3/resources/epic_cda.xml#L248-L250

## Context
CDAs from different regions and providers can be implemented very differently. This is part of a larger effort to make the CDA parser more configurable and adaptable.

## Possible Implementation
1. Add a `SectionCode` enum
```python
class SectionCode(Enum):
    MEDICATION = "10160-0"
```
2. Add `._find_section_by_code()` in `CdaAnnotator`
3. Update `_find_problems_section()`, `_find_medications_section()`, and `_find_allergies_section()`
4. e.g.
```python
def _find_medications_section(self) -> Optional[Section]:
    return (self._find_section_by_template_id(SectionId.MEDICATION.value) or self._find_section_by_code(SectionId.MEDICATION.value))
```
## Alternative Implementation
We can also make the `templateId` and `code` configurable - currently hard-coded.

**Comment by Vortex-21** [comment]
Hey Can you assign me this issue ? Will start working on it right away!

**Comment by jenniferjiangkells** [comment]
👋 @Vortex-21 - assigned you the issue, any questions let me know!

**Comment by jenniferjiangkells** [comment]
@Vortex-21 just checking if you still want to work on this issue! I will unassign you but please still feel free to work on it if you want - we've just decided to to change the issue assignment system.

**Comment by Vortex-21** [comment]
Yes I would still want to work on this issue !

**Comment by Vortex-21** [comment]
![Screenshot 2024-10-18 094011](https://github.com/user-attachments/assets/0dee1884-199b-462b-b5d1-75ba7fbbbe02)

Here in this component , is the code "51847-2" supposed to be the LOINC code for the NOTE enum ? I could get the exact medication, problem and allergy codes but I am not so sure about the "note" code.

Asking this because the section_id does contain NOTE : 
```
class SectionId(Enum):
    PROBLEM = "2.16.840.1.113883.10.20.1.11"
    MEDICATION = "2.16.840.1.113883.10.20.1.8"
    ALLERGY = "2.16.840.1.113883.10.20.1.2"
    NOTE = "1.2.840.114350.1.72.1.200001"
```

**Comment by jenniferjiangkells** [comment]
@Vortex-21 Yes you can assume that's the code for the note section for now!

**Comment by Vortex-21** [comment]
> @Vortex-21 Yes you can assume that's the code for the note section for now!

Yes . Raised the PR using that code only !
