### ISSUE TITLE
Pass timeout as configuration in EHRClient

### ISSUE THREAD

**Issue by jenniferjiangkells** [dotimplement/HealthChain#67]
## Description
In the `EHRClient.send_request` method, we currently have a hardcoded timeout value. We need to modify this to accept a configurable timeout value.

https://github.com/dotimplement/HealthChain/blob/a4beb13020a66fe3b2d1b5555433dfbf0d5480f3/healthchain/clients/ehrclient.py#L153

## Context
This change is important because different environments and use cases may require different timeout settings. For example, in development, we might want a longer timeout for debugging, while in production, we might need stricter timeouts. Making this configurable will benefit other users by allowing them to fine-tune the client's behavior to their specific needs without modifying the core code.

## Possible Implementation
1. Add a `timeout` parameter to the `EHRClient` constructor with a default value:
   ```python
   def __init__(self, ..., timeout: Optional[float] = 10.0):
       self.timeout = timeout
   ```

2. Update the `send_request` method to use the configured timeout:
   ```python
   timeout = httpx.Timeout(self.timeout, read=None)
   ```

3. Update docstrings and type hints accordingly.

4. Modify existing tests and add new ones to cover the timeout configuration.

## Possible Alternatives
1. Instead of a simple float, we could use a more complex timeout configuration object that allows setting connect, read, and write timeouts separately.

2. We could implement a global configuration system for the entire library, where timeout would be just one of many configurable options.

3. We could use environment variables for configuration, allowing users to set timeouts without changing code.

**Comment by rafabelts** [comment]
Hi, I would like to work in the issue

**Comment by jenniferjiangkells** [comment]
@rafabelts Thanks for your interest in contributing! I will unassign you for now as we've decided not to assign issues but please feel free to still work on it - let us know if you start working on it and just open a PR when you're ready 🙂
