### ISSUE TITLE
Add utility functions and validation to ValueSet class

### ISSUE THREAD

**Issue by jenniferjiangkells** [dotimplement/HealthChain#75]
## Description
We need to enhance the `ValueSet ` class with utility functions to make it more flexible and easier to use. This includes adding methods to dynamically add new codes and load value sets from JSON files.

## Context
Values are currently hard-coded - these improvements will make the value sets more maintainable and allow users to extend them without modifying the original code. It will also provide an easier way to manage and update large sets of codes for custom scenarios.

[value_sets/base.py]( https://github.com/dotimplement/HealthChain/blob/032f07e19a4c56deeba7a8bf5e951c9a59113af2/healthchain/data_generators/value_sets/base.py#L4)
[value_sets/medicationcodes.py](https://github.com/dotimplement/HealthChain/blob/032f07e19a4c56deeba7a8bf5e951c9a59113af2/healthchain/data_generators/value_sets/medicationcodes.py#L12)

## Possible Implementation
1. Implement an `.add_code()`utility function to the `ValueSet` class, which allows users to add single a dictionary entry, e.g. `{"code": "774656009", "display": "Aspirin"}`
2. Implement a `.load_from_json()` utility function to the `ValueSet` class, which loads a list of dictionaries containing code and display entries from a json file.
4. Optionally implement validation that entries contain the keys `code` and `display`. This can be implemented as a pydantic class to replace dictionaries, e.g.
```python
from pydantic import BaseModel

class ValueSetEntry(BaseModel):
    code: str
    display: str
```
So the initialization would be something like:

```python
@dataclass
class MedicationRequestMedication(ValueSet):
    ...
    def __post_init__(self):
        default_medications = [
            {"code": "774656009", "display": "Aspirin"},
            {"code": "773455007", "display": "Atorvastatin"},
            # ... (other medications)
        ]
        self.value_set = [ValueSetEntry(**med) for med in default_medications]
```

**Comment by isatyamks** [comment]
hey @jenniferjiangkells  i want to work on this issue can you please assing it to me?

**Comment by jenniferjiangkells** [comment]
@isatyamks Thanks for your interest contributing! We don't assign issues but feel free to get started on this - just open the PR when you're ready! 🙂

**Comment by payo101** [comment]
Alright, so I can just start working on this issue right? @jenniferjiangkells

**Comment by ni9999** [comment]
hey @jenniferjiangkells . Worked on it #90 . Please review it.
