### ISSUE TITLE
Implementing Dark mode Feature

### ISSUE THREAD

**Issue by Prachirsh** [dotimplement/HealthChain#79]
## Description
The dark mode feature allows users to toggle between light and dark themes, enhancing user experience and reducing eye strain, especially in low-light conditions. 

## Context
Dark mode is increasingly popular among web applications and is often a standard feature in modern UI design. Implementing this feature not only improves aesthetics but also aligns with user preferences for readability and comfort.

## Possible Implementation
Create a toggle button (e.g., a switch) that users can click to switch between dark and light modes.

## Possible Alternatives
Custom Themes

O have already added Dark mode in one application. Can you assign it to me?

**Comment by jenniferjiangkells** [comment]
This is not relevant for this project as we have no frontend features
